import { actionText } from '../i18n';
import { NOTE_ACTION_IDS, type NoteActionId } from './note-actions';

const BASE_ACTION_IDS = [
  'scrollDown',
  'scrollUp',
  'scrollLeft',
  'scrollRight',
  'prevPage',
  'nextPage',
  'historyBack',
  'historyForward',
  'followLink',
  'flashText',
  'firstPage',
  'lastPage',
  'halfPageDown',
  'halfPageUp',
  'fullPageDown',
  'fullPageUp',
  'zoomIn',
  'zoomOut',
  'zoomReset',
  'scrollTop',
  'scrollCenter',
  'scrollBottom',
  'openSearch',
  'findNext',
  'findPrevious',
  'prevAnnotation',
  'nextAnnotation',
  'clearSearch',
  'enterVisual',
  'openSelectionActions',
  'enterInsert',
  'exitMode',
  'extendDown',
  'extendUp',
  'extendLeft',
  'extendRight',
  'extendSentenceForward',
  'extendSentenceBackward',
  'extendParagraphForward',
  'extendParagraphBackward',
  'extendWordForward',
  'extendWordBackward',
  'extendLineStart',
  'extendLineEnd',
  'highlightYellow',
  'highlightRed',
  'highlightGreen',
  'highlightBlue',
  'highlightPurple',
  'underlineSelection',
  'addNote',
  'copySelection',
  'searchSelection',
  'swapVisualEnds',
  'editAnnotation',
  'deleteAnnotation',
  'filterYellow',
  'filterRed',
  'filterGreen',
  'filterBlue',
  'filterPurple',
  'filterClear',
  'recolorYellow',
  'recolorRed',
  'recolorGreen',
  'recolorBlue',
  'recolorPurple',
  'yankAnnotation',
  'yankAnnotationComment',
  'openCommandPalette',
  'openNeoSettings',
  'findAllItems',
  'findCollectionItems',
  'findNotes',
  'mainQuickSearch',
  'mainAdvancedSearch',
  'managePlugins',
  'manageSelection',
  'mainReturnContext',
  'mainTrashItems',
  'mainRestoreTrashedItems',
  'mainFocusTree',
  'mainFocusLeft',
  'mainFocusRight',
  'mainFocusItems',
  'mainYankCitekey',
  'mainOpenPDF',
  'closeCurrentTab',
  'addTag',
  'removeTag',
  'toggleTagFilter',
  'clearTagFilters',
  'addToCollection',
  'removeFromCollection',
  'mainEnterSelect',
  'mainToggleSelection',
  'mainClearSelection',
  'mainSelectDown',
  'mainSelectUp',
  'mainSelectFirst',
  'mainSelectLast',
  'mainSelectSwapEnds',
  'mainSelectFinish',
  'mainSelectCancel',
  'mainNavDown',
  'mainNavUp',
  'mainNavFirst',
  'mainNavLast',
  'mainActivate',
  'switchTab',
  'previousTab',
  'nextTab',
  'mainTreeToggle',
  'mainTreeOpenOnly',
  'mainTreeCloseOnly',
  'mainTreeExpand',
  'mainTreeCollapse',
  'mainTreeParent',
  'mainTreeExpandAll',
  'mainTreeCollapseAll',
  'focusReaderSplitLeft',
  'focusReaderSplitDown',
  'focusReaderSplitUp',
  'focusReaderSplitRight',
  'toggleReaderSplitHorizontal',
  'toggleReaderSplitVertical',
  'toggleReaderSidebarOutline',
  'focusReaderSidebar',
  'toggleMarksExplorer',
] as const;

export type BaseActionId = (typeof BASE_ACTION_IDS)[number];
export type ActionId = BaseActionId | NoteActionId;

export const ACTION_IDS = Object.freeze([...BASE_ACTION_IDS, ...NOTE_ACTION_IDS] as ActionId[]);

type ActionLabel = { readonly en: string; readonly 'zh-CN': string };

export const ACTION_LABELS: Readonly<Record<ActionId, ActionLabel>> = Object.freeze(
  Object.fromEntries(
    ACTION_IDS.map((action) => [
      action,
      { en: actionText(action, 'en'), 'zh-CN': actionText(action, 'zh-CN') },
    ]),
  ) as Record<ActionId, ActionLabel>,
);

export type FocusDirection = 'left' | 'down' | 'up' | 'right';

const FOCUS_DIRECTION_BY_ACTION: Partial<Record<ActionId, FocusDirection>> = {
  focusReaderSplitLeft: 'left',
  focusReaderSplitDown: 'down',
  focusReaderSplitUp: 'up',
  focusReaderSplitRight: 'right',
};

export function focusDirectionForAction(action: ActionId | undefined): FocusDirection | null {
  return action ? (FOCUS_DIRECTION_BY_ACTION[action] ?? null) : null;
}

const ACTION_ID_SET = new Set<string>(ACTION_IDS);

export function isActionId(value: unknown): value is ActionId {
  return typeof value === 'string' && ACTION_ID_SET.has(value);
}
